### ISSUE TITLE
会议室预定情况显示！

### ISSUE THREAD

**Issue by liugang926** [007gzs/meeting#3]
如何将会议室预定情况展示给其他人？我应该修改哪些参数？

**Comment by yanshisunshine** [comment]
安装时候出现redis.exceptions.ReadOnlyError: You can't write against a read only slave.
在mysql 创建了 数据库和 表，为什么会有redis ，我多次重启redis 不起作用，不知道为啥

**Comment by 007gzs** [comment]
你可以将会议室分享给别人，只要被人关注了，就可以看到会议室的预定轻狂
