### ISSUE TITLE
django.urls.exceptions.NoReverseMatch: Reverse for 'cool_admin_autocomplete' not found.

### ISSUE THREAD

**Issue by z729063706** [007gzs/meeting#9]
当我在管理页面点击用户编辑时会无法打开页面，出现错误提示网页，命令行输出django.urls.exceptions.NoReverseMatch: Reverse for 'cool_admin_autocomplete' not found.
同时在我使用小程序时会提示网络错误
但是没有报错
求帮忙

**Comment by 007gzs** [comment]
master已修复
